### ISSUE TITLE
Doesn't work on recent ESP32 firmware

### ISSUE THREAD

**Issue by juhi24** [rroemhild/pycom-ruuvitag#4]
It seems the most up to date ESP32 micropython firmware does not have bluetooth capabilities (see https://github.com/micropython/micropython-esp32/issues/222). 

Nevertheless, I'm very curious in trying this module! Where could I get an EPS32 firmware which works with it?

**Comment by rroemhild** [comment]
You are right, there is currently no micropython bluetooth support for the esp32. It looks like only the pycom devices have a working bluetooth stack.

**Comment by juhi24** [comment]
Ok, thanks for the info. Next I plan to explore if some pycom WiPy firmware would work on my device (TTGO v2.0).

**Comment by cirobr** [comment]
Hello,

Have just updated a Pysense/LoPy4 pair to the most recent firmware, then the library apparently stopped working. No errors are found during execution, but three ruuvitags neither whitelisted nor blacklisted are no longer found.

Thanks for advising!

**Comment by cirobr** [comment]
Hello,

Have fixed the issue by downgrading LoPy4 firmware to version 1.17.3.b1.
Current latest version is 1.20.2.rc10.

Regards,

**Comment by rroemhild** [comment]
@cirobr the latest released version works with pycom micropython 1.20.2.r1.

**Comment by rroemhild** [comment]
@juhi24 if this is still an issue for you. I've add a "upstream" MicroPython version that works with the ESP32 devices.

https://github.com/rroemhild/micropython-ruuvitag
