### ISSUE TITLE
how to install ? Bluetooth missing

### ISSUE THREAD

**Issue by minscof** [rroemhild/pycom-ruuvitag#7]
I have trouble with installation,Bluettoth module is not found, but Network module is installed
These are logs

`>>> from ruuvitag.scanner import RuuviTagScanner
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/.micropython/lib/ruuvitag/scanner.py", line 3, in <module>
  File "/home/pi/.micropython/lib/ruuvitag/core.py", line 1, in <module>
ImportError: cannot import name Bluetooth
`
Can you help ?

**Comment by rroemhild** [comment]
Only works on PyCom devices for now. The next MicroPython version comes with official Bluetooth version, but I've not looked into this.

**Comment by rroemhild** [comment]
Here we go. Ruuvitag Scanner for MicroPython on ESP32: https://github.com/rroemhild/micropython-ruuvitag
